# This is a configuration containing default values only. The `config.example.toml` file contains
# a configuration more useful for demonstration purposes.

log-format = 'text'

[server]
pages = 'tcp/localhost:3000'
caddy = 'tcp/localhost:3001'
metrics = 'tcp/localhost:3002'

[storage]
type = 'fs'

[storage.fs]
root = './data'

[limits]
max-site-size = '128MB'
max-manifest-size = '1MB'
max-inline-file-size = '256B'
git-large-object-threshold = '1MB'
max-symlink-depth = 16
update-timeout = '1m0s'
concurrent-uploads = 1024
max-heap-size-ratio = 0.5
forbidden-domains = []
allowed-repository-url-prefixes = []
allowed-custom-headers = ['X-Clacks-Overhead']
allow-basic-auth = false

[audit]
node-id = 0
collect = false
include-ip = ''

[observability]
slow-response-threshold = '500ms'
